package com.novoda.noplayer;

public enum PlayerErrorType {

    INVALID_RESPONSE_CODE,
    MALFORMED_CONTENT,
    FAILED_DRM_DECRYPTION,
    FAILED_DRM_INITIATING,
    FAILED_DRM_REQUEST,
    CONNECTIVITY_ERROR,
    MEDIA_FORMAT_NOT_RECOGNIZED,
    MEDIA_SERVER_DIED,
    MEDIA_SOURCE_ERROR,
    STREAMED_VIDEO_ERROR,
    UNKNOWN

}
