package com.novoda.noplayer;

public enum PlayerErrorType {

    SOURCE,
    CONNECTIVITY,

    DRM,
    CONTENT_DECRYPTION,
    DEVICE_MEDIA_CAPABILITIES,
    RENDERER_DECODER,

    UNEXPECTED,

    MEDIA_PLAYER_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK,
    MEDIA_PLAYER_UNKNOWN_ERROR,
    MEDIA_PLAYER_SERVER_DIED_ERROR,

    UNKNOWN
}
